name: CD

on:
  push:
    branches:
      - main
    paths:
      - "devops/05-gh-deployment-workflow/index.html"
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check index.html exists
        run: |
          if [ -f "devops/05-gh-deployment-workflow/index.html" ]; then
            echo "✅ index.html found"
          else
            echo "❌ index.html not found" 
            exit 1
          fi

      - name: Configure Pages (creates github-pages environment if needed)
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "devops/05-gh-deployment-workflow"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
